version: "3.9"
services:
  gateway:
    build: ./gateway-service
    container_name: campusbot-gateway
    ports:
      - "8000:8000"
    networks:
      - campus-net

  user:
    build: ./user-service
    container_name: campusbot-user
    ports:
      - "8001:8001"
    networks:
      - campus-net

  chat:
    build: ./chat-service
    container_name: campusbot-chat
    ports:
      - "8002:8002"
    networks:
      - campus-net

  knowledge:
    build: ./knowledge-service
    container_name: campusbot-knowledge
    ports:
      - "8003:8003"
    networks:
      - campus-net

  ai:
    build: ./ai-service
    container_name: campusbot-ai
    ports:
      - "8004:8004"
    networks:
      - campus-net

networks:
  campus-net:
    driver: bridge
